baseURL = "https://ismaelnv.com/"
title = "Ismael Navarro - Consultoría Estratégica"
theme = "hugo-coder"
languageCode = "es"
defaultContentLanguage = "es"
paginate = 10
enableEmoji = true
enableRobotsTXT = true

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true

[params]
  author = "Ismael Navarro"
  description = "Consultor Estratégico Valencia | Transformación Digital | Fondos Europeos Next Generation EU | Contratos Públicos | Ex-Oficial Ministerio Defensa | 20+ años liderazgo | Especialista PYMES y Administración Pública"
  keywords = "consultor estratégico valencia,transformación digital pymes,fondos europeos next generation,contratos públicos defensa,ex oficial ejercito consultor,financiación pública empresas,digitalización empresas valencia,consultor sector público,ayudas europeas valencia,licitaciones públicas,modernización empresarial,asesor estratégico españa"
  info = ["Consultor Estratégico", "Transformación Digital", "Financiación Pública", "Ex-Oficial Ministerio Defensa"]
  avatarURL = "images/avatar.jpeg"
  dateFormat = "January 2, 2006"
  since = 2024
  colorScheme = "auto"
  hideColorSchemeToggle = false
  maxSeeAlsoItems = 5

  [params.seo]
    keywords = [
      "consultor estratégico valencia", "consultoria empresarial valencia", "asesor estratégico españa", 
      "consultor transformación digital", "consultor liderazgo empresarial", "consultor gestión cambio",
      "fondos europeos valencia", "ayudas europeas empresas", "subvenciones next generation eu",
      "consultor fondos europeos", "gestión subvenciones públicas", "financiación pública empresas",
      "contratos públicos defensa", "licitaciones sector público", "acceso financiación europea",
      "transformación digital pymes", "digitalización empresas valencia", "consultor tecnológico",
      "implementación sistemas digitales", "modernización empresarial", "estrategia digital",
      "consultor sector defensa", "seguridad empresarial", "ciberseguridad empresas valencia",
      "auditoría seguridad", "consultor ex militar", "análisis riesgos empresariales",
      "consultor administración pública", "asesor sector público", "consultor pymes valencia",
      "transformación digital administración", "modernización sector público",
      "consultor valencia", "consultoria comunidad valenciana", "asesor empresarial españa",
      "consultor castellón alicante", "servicios empresariales levante",
      "como acceder fondos europeos", "ayuda solicitar subvenciones", "consultor next generation eu valencia",
      "transformación digital sector público", "modernización empresas tradicionales",
      "ex oficial ejercito consultor", "experiencia ministerio defensa",
      "gestión integral proyectos europeos", "asesoramiento licitaciones públicas",
      "consultoría compliance normativo", "auditoría procesos empresariales",
      "planificación estratégica empresarial", "optimización recursos empresariales"
    ]

customCSS = []
customSCSS = []
customJS = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/ismael-navarro-valencia/"

[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/isnaval"

[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 3
  url = "mailto:contacto@ismaelnv.com"

[languages]
  [languages.en]
    languageName = "🇬🇧"
    title = "Ismael Navarro - Strategic Consulting"

    [languages.en.params]
      author = "Ismael Navarro"
      description = "Strategic Consultant Valencia Spain | Digital Transformation | European Funds Next Generation EU | Public Contracts | Former Defense Ministry Officer | 20+ years leadership | SME & Public Administration Specialist"
      keywords = "strategic consultant valencia spain,digital transformation sme,european funds next generation,public contracts defense,former military officer consultant,public funding companies,business digitalization valencia,public sector consultant,european grants valencia,public procurement,business modernization,strategic advisor spain"
      info = ["Strategic Consultant", "Digital Transformation", "Public Funding", "Former Defense Ministry Officer"]

    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"

    [[languages.en.menu.main]]
      name = "Services"
      weight = 2
      url = "services/"

    [[languages.en.menu.main]]
      name = "Projects"
      weight = 3
      url = "projects/"

    [[languages.en.menu.main]]
      name = "Funding"
      weight = 4
      url = "funding/"

    [[languages.en.menu.main]]
      name = "Contact"
      weight = 5
      url = "contact/"

  [languages.es]
    languageName = "🇪🇸"
    title = "Ismael Navarro - Consultoría Estratégica"

    [languages.es.params]
      author = "Ismael Navarro"
      description = "Consultor Estratégico | Transformación Digital | Acceso a Financiación Pública | +20 años experiencia en liderazgo | Especialista en Defensa y Seguridad"
      keywords = "consultor estratégico,transformación digital,financiación pública,fondos europeos,contratos públicos,defensa,seguridad,liderazgo empresarial,valencia,españa"
      info = ["Consultor Estratégico", "Transformación Digital", "Financiación Pública", "Ex-Oficial Ministerio Defensa"]

    [[languages.es.menu.main]]
      name = "Sobre mí"
      weight = 1
      url = "about/"

    [[languages.es.menu.main]]
      name = "Servicios"
      weight = 2
      url = "services/"

    [[languages.es.menu.main]]
      name = "Proyectos"
      weight = 3
      url = "projects/"

    [[languages.es.menu.main]]
      name = "Financiación"
      weight = 4
      url = "funding/"

    [[languages.es.menu.main]]
      name = "Contacto"
      weight = 5
      url = "contact/"
